### PR TITLE
Fixed issue #32

### PR DESCRIPTION
**Pull request by glad-dev**
- Added query intent into AndroidManifest

- Added fallback to load the web page in the app itself if the activity can't be resolved

### CODE REVIEW

**Review by eknoes — APPROVED** [review]
Works for me

**Comment by eknoes** [comment]
Thanks for resolving the issue. Will push an update to the Play Store today or tomorrow :)

**Comment by glad-dev** [comment]
Thank you for merging so fast. Looking forward to receive the update :)

**Comment by glad-dev** [comment]
> Thanks for resolving the issue. Will push an update to the Play Store today or tomorrow :)

Have you had time to push the update?  I'm still on version 1.2 which was pushed on Jul 25, 2020. There is no update, even after I joined the Beta

I'm running on the latest Android 12 version

**Comment by eknoes** [comment]
Yes I pushed it, but even after improvements it was the second time declined by Google, as they updated a regulation for News Apps which the app did not fulfill. Unfortunately, their feedback is quite unambigious, so I hope the third try will work.

**Comment by glad-dev** [comment]
Well, that sucks. Hopefully it passes this time

Nevertheless, thank you very much for taking the time to push it two time and responding so fast! I really appreciate it

**Comment by eknoes** [comment]
It passed and is available :)

**Comment by glad-dev** [comment]
> It passed and is available :)

Just received it :)
Thank you very much :)

**Pull request merged**
